version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_key
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null, unique]
  - name: dim_product
    columns:
      - name: product_key
        tests: [not_null, unique]
      - name: product_id
        tests: [not_null, unique]
  - name: dim_seller
    columns:
      - name: seller_key
        tests: [not_null, unique]
      - name: seller_id
        tests: [not_null, unique]
  - name: fact_sales
    columns:
      - name: order_id
        tests: [not_null]
      - name: customer_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_customer')
                field: customer_key
      - name: product_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_product')
                field: product_key
      - name: seller_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_seller')
                field: seller_key
      - name: order_status
        tests:
          - accepted_values:
              arguments:
                values: ['approved', 'canceled', 'created', 'delivered', 'invoiced', 'processing', 'shipped', 'unavailable']
